# Generated by Django 4.0.4 on 2022-04-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.CharField(max_length=200, null=True)),
                ('semester', models.CharField(max_length=200, null=True)),
                ('name', models.CharField(max_length=200, null=True)),
                ('pruefer', models.CharField(max_length=200, null=True)),
                ('datum', models.CharField(max_length=200, null=True)),
                ('startzeit', models.CharField(max_length=200, null=True)),
                ('pruefungsform', models.CharField(max_length=200, null=True)),
                ('dauer', models.CharField(max_length=200, null=True)),
                ('teilnehmerzahl', models.CharField(max_length=200, null=True)),
                ('pruefungsOrdnung', models.CharField(max_length=200, null=True)),
                ('studiengang', models.CharField(max_length=120, null=True)),
                ('fachbereich', models.CharField(max_length=200, null=True)),
                ('abschluss', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
