# Generated by Django 4.0.3 on 2022-04-08 00:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studiengang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fachbereich', models.CharField(choices=[('EI', 'Elektrotechnik und Informatik'), ('G', 'Geodäsie')], max_length=200)),
                ('abschulss', models.CharField(choices=[('BA', 'Bachelor'), ('MA', 'Master')], max_length=20)),
                ('pruefungsOrdnung', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='pruefung',
            name='fachbereich',
        ),
        migrations.AddField(
            model_name='pruefung',
            name='createTime',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruefung',
            name='datum',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruefung',
            name='dauer',
            field=models.IntegerField(default=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruefung',
            name='pnr',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruefung',
            name='pruefer',
            field=models.CharField(default='koch', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruefung',
            name='pruefungsform',
            field=models.CharField(default='pr', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruefung',
            name='teilnehmerzahl',
            field=models.IntegerField(default=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruefung',
            name='updateTime',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Pruefung_Studiengang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pnr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.pruefung', to_field='pnr')),
                ('studiengangid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.studiengang')),
            ],
        ),
    ]
