# Generated by Django 4.0.3 on 2022-04-13 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pruefung_createtime_alter_pruefung_updatetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pruefung',
            name='createTime',
        ),
        migrations.RemoveField(
            model_name='pruefung',
            name='updateTime',
        ),
    ]
