# Generated by Django 4.0.3 on 2022-04-16 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_pruefung_createtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruefung',
            old_name='fachbereich',
            new_name='studiengang',
        ),
    ]
