# Generated by Django 4.0.3 on 2022-04-16 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_fachbereich_pruefung_studiengang'),
    ]

    operations = [
        migrations.AddField(
            model_name='studiengang',
            name='name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
