# Generated by Django 4.0.3 on 2022-04-16 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_pruefung_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefung',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
