# Generated by Django 4.0.3 on 2022-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_pruefung_datum'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefung',
            name='abschulss',
            field=models.CharField(choices=[('BA', 'Bachelor'), ('MA', 'Master')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pruefung',
            name='fachbereich',
            field=models.CharField(choices=[('EI', 'Elektrotechnik und Informatik'), ('G', 'Geodäsie')], default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='pruefung',
            name='studiengang',
        ),
        migrations.AddField(
            model_name='pruefung',
            name='studiengang',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Studiengang',
        ),
    ]
