# Generated by Django 4.0.3 on 2022-04-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_pruefung_abschulss_pruefung_fachbereich_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefung',
            name='dauer',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='semester',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='teilnehmerzahl',
            field=models.IntegerField(null=True),
        ),
    ]
