# Generated by Django 4.0.3 on 2022-04-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_pruefung_pnr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefung',
            name='abschulss',
            field=models.CharField(choices=[('BA', 'Bachelor'), ('MA', 'Master')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='fachbereich',
            field=models.CharField(choices=[('EI', 'Elektrotechnik und Informatik'), ('G', 'Geodäsie')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='pruefer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='pruefungsOrdnung',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='pruefungsform',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='studiengang',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
