# Generated by Django 4.0.3 on 2022-04-16 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_pruefung_abschulss_alter_pruefung_fachbereich_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefung',
            name='semester',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
