# Generated by Django 4.0.3 on 2022-04-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_pruefung_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefung',
            name='dauer',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='pnr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='pruefungsOrdnung',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='teilnehmerzahl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
