# Generated by Django 4.0.3 on 2022-04-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_pruefung_dauer_alter_pruefung_pnr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pruefung',
            name='datum',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
