# Generated by Django 4.0.3 on 2022-04-16 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_pruefung_datum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pruefung',
            old_name='abschulss',
            new_name='abschluss',
        ),
    ]
