# Generated by Django 4.0.3 on 2022-04-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_abschulss_pruefung_abschluss'),
    ]

    operations = [
        migrations.AddField(
            model_name='pruefung',
            name='startzeit',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='abschluss',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pruefung',
            name='fachbereich',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
